# Generated by Django 5.2.1 on 2025-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='isVegetarian',
            new_name='Took_water_today',
        ),
        migrations.RemoveField(
            model_name='calorie',
            name='water',
        ),
        migrations.AddField(
            model_name='calorie',
            name='Vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
